#!/usr/bin/env bash

echo "Downloading files..."
wget -q https://raw.githubusercontent.com/NikoboiNFTB/GitHub-Tools/refs/heads/main/shell/pull && chmod -f +x pull
wget -q https://raw.githubusercontent.com/NikoboiNFTB/GitHub-Tools/refs/heads/main/shell/push && chmod -f +x push
wget -q https://raw.githubusercontent.com/NikoboiNFTB/GitHub-Tools/refs/heads/main/shell/.disable-ssh && chmod -f +x .disable-ssh
wget -q https://raw.githubusercontent.com/NikoboiNFTB/GitHub-Tools/refs/heads/main/shell/.enable-ssh && chmod -f +x .enable-ssh
echo "Files downloaded"

echo "Cleaning up..."
rm -f setup-author
echo "Cleanup done"

echo "All done!"

echo "Tip: The files can be renamed to whatever you want"
