#!/usr/bin/env bash
set -e

read -rp "Install directory: " install_dir
install_dir="${install_dir/#\~/$HOME}"

if [ -z "$install_dir" ]; then
    echo "You didn’t type anything."
    exit 1
fi

if [ ! -d "$install_dir" ]; then
    echo "Directory doesn’t exist. Making it for you."
    mkdir -p "$install_dir"
fi

cd "$install_dir"

echo "Downloading files..."

wget -q https://github.com/NikoboiNFTB/GitHub-Tools/raw/refs/heads/main/shell/.disable-ssh
chmod -f +x .disable-ssh

wget -q https://github.com/NikoboiNFTB/GitHub-Tools/raw/refs/heads/main/shell/.enable-ssh
chmod -f +x .enable-ssh

wget -q https://github.com/NikoboiNFTB/GitHub-Tools/raw/refs/heads/main/shell/all-pull
chmod -f +x all-pull

wget -q https://github.com/NikoboiNFTB/GitHub-Tools/raw/refs/heads/main/shell/all-push
chmod -f +x all-push

echo "Files downloaded"

echo "Cleaning up..."
rm -f setup
echo "Cleanup done"

echo "All done!"
